const myVideoContainer = document.getElementById("myVideoContainer");
const myVideoElement = document.getElementById("myVideo");
let pc; // making pc as a global variable so we can access this in the console
async function handleNegotiationNeeded() {
  const offer = await pc.createOffer(); // an offer is an SDP (Session Description Protocol) blob generated by a peer to initiate a connection
  console.log(offer);
  // const modifiedSDP = modifySDPForrecvonly(offer.sdp);
  // await pc.setLocalDescription(
  //   //modifing the sdp returned by seting a offer
  //   new RTCSessionDescription({
  //     type: "offer",
  //     sdp: modifiedSDP,
  //   }),
  // );
  await pc.setLocalDescription(offer); // as we set the localdiscription of pc to offer the icegathering process starts and it gathers some ice candidates(routes)
}
const initiateRTC = async () => {
  try {
    let localStream = await navigator.mediaDevices.getUserMedia({
      video: true,
      audio: true,
    });
    myVideoElement.srcObject = localStream;
    //we need to provide our RTCPeerConnection a stun server that helps to connect with others peer which converts private IP to public and Vice versa
    const WebRTCconfigurationObject = {
      iceServers: [
        // iceserver is an array of ice servers
        {
          urls: ["stun:stun.l.google.com:19302"], // we can have arrays of different stun server urls
        },
      ],
    };
    pc = new RTCPeerConnection(WebRTCconfigurationObject);
    //add event listener that indicates when to starts signaling after negotiation
    pc.addEventListener("negotiationneeded", handleNegotiationNeeded);
    const tracks = localStream.getTracks(); //our local stream has the audio and video track
    tracks.forEach((offer) => {
      //adding each track to the rtcpeerconection object
      pc.addTrack(offer);
      console.log("Tracks are added to the RTCPeerConnection");
    });

    const stats = await pc.getStats(); //A Promise which resolves with an RTCStatsReport object providing connection statistics
    stats.forEach((report) => {
      console.log(report);
    });

    console.log(pc.iceGatheringState);
    pc.addEventListener("icecandidate", (eventObject) => {
      console.log("ICE RECIEVED", eventObject.candidate); //display all the routes gathered by ice candidates
    });
    console.log(pc.iceGatheringState);
  } catch (error) {
    console.log(error);
  }
};
myVideoContainer.addEventListener("click", initiateRTC);

function getMediadevices() {
  navigator.mediaDevices.enumerateDevices().then((deviceArray) => {
    deviceArray.forEach((device) => {
      console.log(device);
    });
  });
}
function modifySDPForrecvonly(sdp) {
  const Lines = sdp.split("\n");
  for (let i = 0; i < Lines.length; i++) {
    if (Lines[i].startsWith("a=sendrecv")) {
      Lines[i] = "a=recvonly"; //modify the sendrcv with recvonly
      break; // only modify the first occurence
    }
  }
  return Lines.join("\n");
}
